apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
    - name: http
      port: 80 # Porta exposta pelo serviço (dentro do cluster)
      targetPort: 8080 # Porta usada no pod (onde sua app Go está escutando)
      protocol: TCP
